### ISSUE TITLE
Truncate existing file

### ISSUE THREAD

**Issue by cry999** [cry999/gopenapi#2]
Trashes remain when output file is overwritten by shorter content.

Example:

before:

```yaml
...
security:
  - token: []
```

after:

```yaml
...
security:
  - token: []
rity:
  - token: []
```
